
# This is a basic workflow that is manually triggered

name: 01-manual-s3-bucket-tfstate-setup

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_STATE_BUCKET_NAME : ${{ secrets.TF_STATE_BUCKET_NAME }}

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs: {}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  setup_bucket:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    container:
      image: amazon/aws-cli:2.0.7
    steps:
    - name: Create bucket
      run: 'aws s3api create-bucket --bucket ${{ env.TF_STATE_BUCKET_NAME }} --region ${{ env.AWS_DEFAULT_REGION }} --acl private --object-lock-enabled-for-bucket --output yaml'

    - name: Bucket tagging
      run: 'aws s3api put-bucket-tagging --bucket ${{ env.TF_STATE_BUCKET_NAME }} --region ${{ env.AWS_DEFAULT_REGION }} --tagging "TagSet=[{Key=Name,Value=${{ env.TF_STATE_BUCKET_NAME }}}]" --output yaml'
          
    - name: Bucket versioning
      run: 'aws s3api put-bucket-versioning --bucket ${{ env.TF_STATE_BUCKET_NAME }} --region ${{ env.AWS_DEFAULT_REGION }}  --versioning-configuration Status=Enabled --output yaml'
     
    - name: Bucket encryption
      run: 'aws s3api put-bucket-encryption --bucket ${{ env.TF_STATE_BUCKET_NAME }} --region ${{ env.AWS_DEFAULT_REGION }} --server-side-encryption-configuration ''{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'' --output yaml'
          

